[package]
name = "app"
version = "4.0.0"
description = "A Tauri App"
authors = ["you"]
license = "GPLv3"
repository = ""
default-run = "app"
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-rc.0", features = [] }

[dependencies]
open = "2.0.2"
regex = "1.5.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-rc.0", features = ["api-all"] }
winreg = "0.10.1"
winapi = { version = "0.3.9", features = ["winnls"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
