name: "Tauri"
on:
  push:
    branches: [ main ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ main ]

env:
  TAURI_SCRIPT: pnpm tauri

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}
    # https://github.com/tauri-apps/tauri-action#testing-the-build
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.0-dev libssl-dev libgtk-3-dev libappindicator3-dev librsvg2-dev
      - name: Pnpm install
        run: |
          corepack enable
          pnpm install
      - name: Cargo build
        run: |
          cd src-tauri
          cargo build
      - name: Tauri build bundle & release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: tauri-apps/tauri-action@v0.2
        with:
          tauriScript: ${{ env.TAURI_SCRIPT }}
          tagName: v__VERSION__
          releaseName: Release v__VERSION__
          releaseDraft: true
