name: "Tauri"
on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            bundle: "msi/vscch*.msi"
            exe: "vscch.exe"
          - os: ubuntu-latest
            bundle: "appimage/vscch*.AppImage"
            exe: "vscch"
          - os: macos-latest
            bundle: "dmg/vscch*.dmg"
            exe: "vscch"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.0-dev libssl-dev libgtk-3-dev libappindicator3-dev librsvg2-dev
      - name: Pnpm install
        run: |
          corepack enable
          pnpm install
      - name: Tauri build
        run: pnpm tauri build
      - name: Pack executable
        if: ${{ github.ref_type == 'tag' }}
        run: |
          cd ${{ github.workspace }}
          7z a src-tauri/target/vscch_${{ github.ref_name }}_${{ runner.os }}.7z src-tauri/target/release/${{ matrix.exe }} ${{ github.workspace }}/LICENSE
      - name: Release
        if: ${{ github.ref_type == 'tag' }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/src-tauri/target/release/bundle/${{ matrix.bundle }}
            ${{ github.workspace }}/src-tauri/target/vscch*.7z
          draft: true
