name: "Tauri"
on:
  push:
    branches: [ main ]
    tags: [ "*" ]
  pull_request:
    branches: [ main ]

env:
  TAURI_SCRIPT: pnpm tauri
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            bundle: "vscch.exe"
          - os: ubuntu-latest
            bundle: "bundle/appimage/vscch*.AppImage"
          - os: macos-latest
            bundle: "bundle/dmg/vscch*.dmg"

    runs-on: ${{ matrix.os }}
    # https://github.com/tauri-apps/tauri-action#testing-the-build
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.0-dev libssl-dev libgtk-3-dev libappindicator3-dev librsvg2-dev
      - name: Pnpm install
        run: |
          corepack enable
          pnpm install
      - name: Tauri build
        run: pnpm tauri build
      - name: Release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/src-tauri/target/release/${{ matrix.bundle }}
          draft: true
