name: "Tauri"
on:
  push:
    branches: [ main ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}
    # https://github.com/tauri-apps/tauri-action#testing-the-build
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: Pnpm install
        run: |
          corepack enable
          pnpm install
      - name: Tauri build
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: tauri-apps/tauri-action@v0
      - name: Tauri build & release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: tauri-apps/tauri-action@v0
        with:
          tagName: v__VERSION__
          releaseName: Release v__VERSION__
          releaseDraft: true
